# -*- coding: utf-8 -*-
"""TTS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Cwp9lVrz98xhiIeEcHhbywbJVNpoYA4
"""

!pip install tts

pip install TTS

! git clone https://github.com/coqui-ai/TTS.git

! pip install -r TTS/requirements.txt

import torch
from TTS.api import TTS

# Get device
device = "cuda" if torch.cuda.is_available() else "cpu"

# List available 🐸TTS models
print(TTS().list_models())

# Init TTS
tts = TTS("tts_models/multilingual/multi-dataset/xtts_v2").to(device)

# Run TTS
# ❗ Since this model is multi-lingual voice cloning model, we must set the target speaker_wav and language
# Text to speech list of amplitude values as output
# wav = tts.tts(text="Hello world!", speaker_wav="/content/WhatsApp Ptt 2024-10-12 at 3.11.05 PM.mp3", language="en")
# Text to speech to a file
tts.tts_to_file(text="Hello hack dearborn", speaker_wav="/content/WhatsApp Ptt 2024-10-12 at 3.11.05 PM.mp3", language="en", file_path="output.wav")

! cd TTS